language: python
dist: trusty
sudo: false
addons:
  postgresql: "9.5"
services:
  - postgresql
python:
  - "2.7"
  - "3.5"
  - "3.6"
env:
  - DJANGO_VERSION=1.9.12
  - DJANGO_VERSION=1.10.6
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r tests/requirements.pip
  - pip install coveralls
  - pip install flake8
after_script:
  - coveralls
script:
  - flake8 --exclude=migrations .
  - coverage run --source=simple_log --omit='simple_log/management/*' manage.py test tests;
