language: python
dist: trusty
sudo: false
addons:
  postgresql: "9.5"
services:
  - postgresql
python:
  - 2.7
  - 3.5
  - 3.6

install:
  - pip install tox-travis

after_script:
  - coveralls

script:
  - coverage run --source=simple_log --omit='simple_log/management/*,simple_log/templates/*,simple_log/admin.py' tox
